title: Ava Li
description: ğŸ´A Data Analyst & Experienced Chef | Leveraging culinary precision and data science skills to cook up insights with SQL, Python, Tableau, and PowerBIğŸ“Š
theme: jekyll-theme-cayman
